# Generated by Django 4.2.3 on 2023-07-26 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtyAvailable', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=100)),
                ('isSaleable', models.BooleanField(default=False)),
            ],
        ),
    ]
